import math

# Parameters
BED_TEMP = 50          # °C
START_Y = 80.0        # mm
END_Y = 130.0         # mm (50 mm travel)
TOTAL_HOURS = 10.0
FEEDRATE_MM_PER_S = 50.0  # 50 mm in 1 s each way -> 2 s round trip
FEEDRATE = FEEDRATE_MM_PER_S * 60.0  # mm/min for G-code
CYCLE_TIME_SECONDS = (END_Y - START_Y) / FEEDRATE_MM_PER_S * 2.0  # there and back

total_seconds = TOTAL_HOURS * 3600.0
cycles = int(total_seconds / CYCLE_TIME_SECONDS)

filename = "prusa_mini_bed_oscillate_10h.gcode"

lines = []

lines.append("; Prusa Mini bed oscillation test")
lines.append("; Generated by ChatGPT helper")
lines.append(f"; Bed temp: {BED_TEMP}C")
lines.append(f"; Y travel: {START_Y} -> {END_Y} (50 mm)")
lines.append(f"; Target cycle time (there-and-back): {CYCLE_TIME_SECONDS} s")
lines.append(f"; Total duration: {TOTAL_HOURS} h")
lines.append(f"; Estimated cycles: {cycles}")
lines.append("")
lines.append("M104 S0            ; ensure hotend heater is off")
lines.append(f"M140 S{BED_TEMP}   ; set bed temperature")
# lines.append(f"M190 S{BED_TEMP}   ; wait for bed to reach temperature")
lines.append("G90                ; absolute positioning")
lines.append("G21                ; units in mm")
lines.append("G28 Y              ; home Y axis only")
lines.append("G28 Z              ; home Z axis")
lines.append("G1 Z170 F1000      ; move extruder up to be out of the way")
lines.append(f"G1 Y{START_Y:.2f} F3000   ; move to starting Y position")
lines.append("")

for i in range(cycles):
    lines.append(f"G1 Y{END_Y:.2f} F{FEEDRATE:.0f}   ; cycle {i+1} forward")
    lines.append(f"G1 Y{START_Y:.2f} F{FEEDRATE:.0f}   ; cycle {i+1} back")

lines.append("")
lines.append("M140 S0            ; turn off bed heater")
lines.append("M84                ; disable motors")
lines.append("; End of bed oscillation test")

with open(filename, "w") as f:
    f.write("\n".join(lines) + "\n")
